output: "{{.Dir}}/README.md"
header: |+
  [![CI](https://github.com/go-coldbrew/grpcpool/actions/workflows/go.yml/badge.svg)](https://github.com/go-coldbrew/grpcpool/actions/workflows/go.yml)
  [![Go Report Card](https://goreportcard.com/badge/github.com/go-coldbrew/grpcpool)](https://goreportcard.com/report/github.com/go-coldbrew/grpcpool)
  [![GoDoc](https://pkg.go.dev/badge/github.com/go-coldbrew/grpcpool.svg)](https://pkg.go.dev/github.com/go-coldbrew/grpcpool)
  [![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)

